pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            name = "Caofangkuai's Maven"
            url 'https://mvn.cfknb.vip'
        }
        maven { url 'https://jcenter.bintray.com' }
    }
}
rootProject.name = "SuperSys"
include ':app'
